### ISSUE TITLE
Improve keyboard sizing and positioning

### ISSUE THREAD

**Issue by menzy314** [menzy314/geiryn#5]
Especially important for mobile devices, where screen sizes vary and we need to use all the space we have.

**Comment by menzy314** [comment]
- Empty space at the bottom of the screen. The keyboard should be there
- The keyboard should perhaps be a little taller on this device
- The keyboard should use 100% of the width

![phonescreenshot](https://user-images.githubusercontent.com/115681307/196074989-b4802ea1-d6fd-4de5-90d6-ee255ef57ff4.jpg)

**Comment by Tchanders** [comment]
Do you know if this has been fixed? I tested it out on a couple of device sizes (using developer tools on my desktop browser) and the keyboard always seemed to be at the bottom, and full width.

**Comment by menzy314** [comment]
Thanks for commenting! Ok, I'll close this issue then
