### ISSUE TITLE
Clicking on consecutive letters that could be a digraph but aren't

### ISSUE THREAD

**Issue by Tchanders** [menzy314/geiryn#9]
Hello! Thanks for this nicely-written game, which is also fun to play!

I was trying to guess "T A N G O" by clicking on the keyboard, but found that adding "G" after "N" always made a digraph, so my guess looked like a 4-letter word: "T A NG O".

It looks like this happens in `Model.pushLetter`: https://github.com/menzy314/geiryn/blob/main/src/geiryn.Model.js#L64

I see that when the user is typing on their keyboard, they can add a space to show they mean two separate letters. I wondered: if the user clicks on "N" then "G" rather than on "NG", should that be interpreted as two separate letters?

If so, perhaps when `View.onClick` calls `Model.pushLetter`, `Model.maybeDigraph` could be set to `false`?

**Comment by menzy314** [comment]
Thanks for reporting this! I just fixed it: 400651416f0d268ce1bca53651d4621049ba7d35
